### ISSUE TITLE
if condition needs an else clause or it will crash

### ISSUE THREAD

**Issue by Nicd** [CrowdHailer/eex_html#3]
If you use an `if` structure, you need to add an `else` clause, or `nil` will be added to the output, which will crash when the content is attempted to convert to string.

For example here, the empty `else` clause is required, to return an empty string instead of `nil`:

```eex
<%= raw(if ... do %>
  <%= ... %>
<% else %>
<% end) %>
```

**Comment by CrowdHailer** [comment]
Can you write a test case. 

If it's possible to do a small one add it as a doc test here 
https://github.com/CrowdHailer/eex_html/blob/master/lib/eex_html/engine.ex#L26

Be good to have several test cases.
- two without an else clause, predicate true/false
- two with an else clause, again predicate true/false

If the PR is open with desired behaviour in tests it's really easy for someone to pick it up

**Comment by Nicd** [comment]
This no longer occurs on the latest version for some reason so I'm closing this issue.

**Comment by CrowdHailer** [comment]
well thats handy :+1
